### ISSUE TITLE
Error in calling the gui

### ISSUE THREAD

**Issue by mohammad-albarham** [linuxscout/adawat-latex#4]
This error appears after when using `python adawat-latex-gui.py`
```
(adawat-latex) D:\1. GitHub\adawat-latex>python adawat-latex-gui.py
Traceback (most recent call last):
  File "adawat-latex-gui.py", line 393, in <module>
    sys.exit(main(sys.argv))
  File "adawat-latex-gui.py", line 385, in main
    my_gui = myToolbox(root)
  File "adawat-latex-gui.py", line 64, in __init__
    self.entry = Text(master, height=15, width=70, font=myfont)
  File "C:\Users\moham\anaconda3\lib\tkinter\__init__.py", line 3554, in __init__
    Widget.__init__(self, master, 'text', cnf, kw)
  File "C:\Users\moham\anaconda3\lib\tkinter\__init__.py", line 2567, in __init__
    self.tk.call(
esources/fonts/AmiriTypewriter-"ger but got "GitHubdawat-latex
```

**Comment by linuxscout** [comment]
Salam,
Solved it,
thank you for your interest.

**Comment by mohammad-albarham** [comment]
Salam, 
Thank you very much.

It seems that the error is not resolved.

**Comment by linuxscout** [comment]
I make a mistake on file location,
I corrected it, can you confirm?

**Comment by mohammad-albarham** [comment]
No it doesn't work. Same error appears.

**Comment by linuxscout** [comment]
I thinks it's a windows OS path related problem,
I tried to fix it,
please try again.

**Comment by linuxscout** [comment]
Thank you for solving it
